### ISSUE TITLE
[a52] Strange behavior with 5.1 surround on ALC1220

### ISSUE THREAD

**Issue by davidebeatrici** [alsa-project/alsa-plugins#21]
I originally encountered the issue ~1 year ago, when I started using a motherboard with an ALC1220 on it.

The out-of-box experience was flawless: I simply connected the optical SPDIF cable to my amplifier/receiver and stereo sound immediately worked.

Once I switched to 5.1 surround, audio output became extremely fast; even videos were affected by it, to the point that they were being reproduced in seconds instead of minutes.

After a few days of research and experiments I managed to workaround the issue by replacing the content of `60-a52-encoder.conf` with:
```
pcm.a52 {
	@args [CARD]
	@args.CARD {
		type string
        }
	type rate
	slave {
		pcm {   
			type a52
			card $CARD
		}
		rate 48000
	}
}
pcm.pulse {
	type pulse
}
ctl.pulse {
	type pulse
}
pcm.!default {
	type pulse
}
ctl.!default {
	type pulse
}
```

Based on https://help.ubuntu.com/community/DigitalAC-3Pulseaudio#Configuring_asound.conf.

After that, I wanted to investigate the cause and report my findings to either ALSA or PulseAudio (depending on the results).

Unfortunately that never happened and I kinda forgot about it, as [libasound2-plugins](https://packages.debian.org/bullseye/libasound2-plugins) was updated a single time in the past year and thus I only had to replace the file's content once more.

Fast-forward to today: I switch from PulseAudio to PipeWire and while troubleshooting https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/1143 I decided to try to restore the original file.

Interestingly, the behavior is different compared to PulseAudio: audio, instead of being fast, is crackling. It's basically as if a frame every two is being skipped.

Unfortunately PipeWire reports no errors whatsoever.

**Comment by perexg** [comment]
https://github.com/alsa-project/alsa-plugins/pull/8 was merged.

**Comment by davidebeatrici** [comment]
Please note that the first commit causes audio not to work with PipeWire.

**Comment by davidebeatrici** [comment]
Related issue: https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/1554

Could you tag a new version, please? As of the latest commit in `master` the issue appears to be completely fixed.
