### ISSUE TITLE
Undeclarated constant

### ISSUE THREAD

**Issue by unknown2045** [alsa-project/alsa-plugins#24]
Hi,
I am trying to install the alsa-plugins, when I do the make command I get the following errors:

![Captura de pantalla de 2021-06-10 13-52-37](https://user-images.githubusercontent.com/85682900/121520376-229ecb00-c9f3-11eb-9230-3f5ace4c3042.png)

How can I solve it?

Thanks in advance!

**Comment by perexg** [comment]
Install kernel headers.

**Comment by unknown2045** [comment]
> Install kernel headers.

I forgot mentioning it but I have already installed and updated them. 

I have a Ubuntu 18.04.5 with  5.4.0-74 generic kernel. Is It a valid kernel?

Thanks.

**Comment by perexg** [comment]
```
$ grep SCM_TXTIME /usr/include/asm-generic/*.h
/usr/include/asm-generic/socket.h:#define SCM_TXTIME		SO_TXTIME
```

For the specific distribution support ask in the appropriate forum.

**Comment by perexg** [comment]
Dup of #4 .
