### ISSUE TITLE
Question about upmix plugin

### ISSUE THREAD

**Issue by krumpfwylg** [alsa-project/alsa-plugins#25]
Hi, I've noticed the [latest commits](https://github.com/alsa-project/alsa-plugins/pull/2) done to the upmix plugin, but there's something I don't understand.
Line 24 of pcm_upmix.c is _#define UPMIX_PCM_FORMAT	SND_PCM_FORMAT_S16_ 
Does that mean the upmix plugin is still only capable of using S16_LE format ?
Or does the UPMIX_PCM_FORMAT value can get changed to S32_LE by tweaking it in asoundrc file ?

**Comment by perexg** [comment]
> Hi, I've noticed the [latest commits](https://github.com/alsa-project/alsa-plugins/pull/2) done to the upmix plugin, but there's something I don't understand.
> Line 24 of pcm_upmix.c is _#define UPMIX_PCM_FORMAT SND_PCM_FORMAT_S16_
> Does that mean the upmix plugin is still only capable of using S16_LE format ?

Yes. But you can change source.

> Or does the UPMIX_PCM_FORMAT value can get changed to S32_LE by tweaking it in asoundrc file ?

No.

**Comment by krumpfwylg** [comment]
In the future, would that be possible for the upmix plugin to get the format information S16/S32/other (with a default set to S16) from the asoundrc file, allowing the user to change format in a more friendly way than having to patch & recompile ? 
Thanks for answers :)
