### ISSUE TITLE
regression: aplay -L missing pulse in 1.2.1

### ISSUE THREAD

**Issue by higuita** [alsa-project/alsa-plugins#3]
Before 1.2, `aplay -L` showed a pulse pcm. After the commit 
https://github.com/alsa-project/alsa-plugins/commit/b0f9c353c7cc9cffb77e7a7b00545ad00f4599fb
pulse is missing from the pcm list. This may break some apps, war thunder (used fmod) game stopped seeing pulse and only tried to use alsa directly

if i comment out the below line in /usr/share/alsa/alsa.conf.d/50-pulseaudio.conf
`@args [ DEVICE ]`

`aplay -L` show again the pulse pcm

another workaround is to add this to the `/etc/asound.conf` :
```
pcm.!pulse {
    type pulse
    hint {
        show on
        description "PulseAudio Sound Server"
    }
}
```

**Comment by perexg** [comment]
Fixed in https://github.com/alsa-project/alsa-lib/commit/5ee5ef31b5ff3fb7c904054cb9cac7478a727f7c . Unfortunately, it's a bug in alsa-lib.
