### ISSUE TITLE
slow audio when plug/unplug external USB audio device

### ISSUE THREAD

**Issue by jmtrivial** [alsa-project/alsa-plugins#33]
Dear Developers,

I am using a debian testing, and tried a couple of libasound2-plugins versions (deb marillat versions, unstable version), but this bug is still present.
I am using an external USB audio device, and pulseaudio for usual audio usages (browser, player, etc). 
When pulsaudio starts, everything is fine with the audio system: when a sound is played, everything is ok.
Even if I unplug the usb device, the audio file is still played in the internal sound card with a correct bitrate.
Unfortunalely, when I replug the USB audio device, the audio file is now played with a slow speed, as if the bitrate was not correctly interpreted;

I tried several settings in the /etc/pulse/daemon.conf without success: trying to change defaultt-sample-rate / alternate-sample-rate to the same value or to different values such as 44100 and 48000, using avoid-resampling=yes or not.

Here is the output of "pactl info":

Server String: /run/user/1000/pulse/native
Library Protocol Version: 34
Server Protocol Version: 34
Is Local: yes
Client Index: 9
Tile Size: 65472
User Name: jm
Host Name: L-16V52X2
Server Name: pulseaudio
Server Version: 14.2
Default Sample Specification: float32le 2ch 44100Hz
Default Channel Map: front-left,front-right
Default Sink: alsa_output.usb-PreSonus_AudioBox_22_VSL_2214-00.analog-stereo
Default Source: alsa_input.usb-PreSonus_AudioBox_22_VSL_2214-00.analog-stereo

Here is the output of "pacmd list-sinks" while the system is playing a slow speed audio (after usb unplug / plug):

2 sink(s) available.
  * index: 0
        name: <alsa_output.usb-PreSonus_AudioBox_22_VSL_2214-00.analog-stereo>
        driver: <module-alsa-card.c>
        flags: HARDWARE DECIBEL_VOLUME LATENCY DYNAMIC_LATENCY
        state: SUSPENDED
        suspend cause: IDLE
        priority: 9049
        volume: front-left: 65536 / 100% / 0,00 dB,   front-right: 65536 / 100% / 0,00 dB
                balance 0,00
        base volume: 65536 / 100% / 0,00 dB
        volume steps: 65537
        muted: no
        current latency: 0,00 ms
        max request: 0 KiB
        max rewind: 0 KiB
        monitor source: 0
        sample spec: s32le 2ch 44100Hz
        channel map: front-left,front-right
                     Stéréo
        used by: 0
        linked by: 0
        configured latency: 0,00 ms; range is 0,50 .. 2000,00 ms
        card: 0 <alsa_card.usb-PreSonus_AudioBox_22_VSL_2214-00>
        module: 6
        properties:
                alsa.resolution_bits = "32"
                device.api = "alsa"
                device.class = "sound"
                alsa.class = "generic"
                alsa.subclass = "generic-mix"
                alsa.name = "USB Audio"
                alsa.id = "USB Audio"
                alsa.subdevice = "0"
                alsa.subdevice_name = "subdevice #0"
                alsa.device = "0"
                alsa.card = "1"
                alsa.card_name = "AudioBox 22 VSL"
                alsa.long_card_name = "PreSonus AudioBox 22 VSL at usb-0000:00:14.0-2.2, high speed"
                alsa.driver_name = "snd_usb_audio"
                device.bus_path = "pci-0000:00:14.0-usb-0:2.2:1.0"
                sysfs.path = "/devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2.2/1-2.2:1.0/sound/card1"
                udev.id = "usb-PreSonus_AudioBox_22_VSL_2214-00"
                device.bus = "usb"
                device.vendor.id = "194f"
                device.vendor.name = "PreSonus Audio Electronics, Inc."
                device.product.id = "0101"
                device.product.name = "AudioBox 22 VSL"
                device.serial = "PreSonus_AudioBox_22_VSL_2214"
                device.string = "front:1"
                device.buffering.buffer_size = "705600"
                device.buffering.fragment_size = "352800"
                device.access_mode = "mmap+timer"
                device.profile.name = "analog-stereo"
                device.profile.description = "Stéréo analogique"
                device.description = "AudioBox 22 VSL Stéréo analogique"
                module-udev-detect.discovered = "1"
                device.icon_name = "audio-card-usb"
        ports:
                analog-output: Analog Output (priority 9900, latency offset 0 usec, available: unknown)
                        properties:

        active port: <analog-output>
    index: 1
        name: <alsa_output.pci-0000_00_1f.3.analog-stereo>
        driver: <module-alsa-card.c>
        flags: HARDWARE HW_MUTE_CTRL HW_VOLUME_CTRL DECIBEL_VOLUME LATENCY DYNAMIC_LATENCY
        state: SUSPENDED
        suspend cause: IDLE
        priority: 9039
        volume: front-left: 52428 /  80% / -5,81 dB,   front-right: 52428 /  80% / -5,81 dB
                balance 0,00
        base volume: 65536 / 100% / 0,00 dB
        volume steps: 65537
        muted: no
        current latency: 0,00 ms
        max request: 0 KiB
        max rewind: 0 KiB
        monitor source: 2
        sample spec: s32le 2ch 44100Hz
        channel map: front-left,front-right
                     Stéréo
        used by: 0
        linked by: 0
        configured latency: 0,00 ms; range is 0,50 .. 2000,00 ms
        card: 1 <alsa_card.pci-0000_00_1f.3>
        module: 7
        properties:
                alsa.resolution_bits = "32"
                device.api = "alsa"
                device.class = "sound"
                alsa.class = "generic"
                alsa.subclass = "generic-mix"
                alsa.name = "ALC3246 Analog"
                alsa.id = "ALC3246 Analog"
                alsa.subdevice = "0"
                alsa.subdevice_name = "subdevice #0"
                alsa.device = "0"
                alsa.card = "0"
                alsa.card_name = "HDA Intel PCH"
                alsa.long_card_name = "HDA Intel PCH at 0xec348000 irq 141"
                alsa.driver_name = "snd_hda_intel"
                device.bus_path = "pci-0000:00:1f.3"
                sysfs.path = "/devices/pci0000:00/0000:00:1f.3/sound/card0"
                device.bus = "pci"
                device.vendor.id = "8086"
                device.vendor.name = "Intel Corporation"
                device.product.id = "9d71"
                device.product.name = "Sunrise Point-LP HD Audio"
                device.form_factor = "internal"
                device.string = "front:0"
                device.buffering.buffer_size = "705600"
                device.buffering.fragment_size = "352800"
                device.access_mode = "mmap+timer"
                device.profile.name = "analog-stereo"
                device.profile.description = "Stéréo analogique"
                device.description = "Audio interne Stéréo analogique"
                module-udev-detect.discovered = "1"
                device.icon_name = "audio-card-pci"
        ports:
                analog-output-speaker: Speakers (priority 10000, latency offset 0 usec, available: unknown)
                        properties:
                                device.icon_name = "audio-speakers"
                analog-output-headphones: Headphones (priority 9900, latency offset 0 usec, available: no)
                        properties:
                                device.icon_name = "audio-headphones"
        active port: <analog-output-speaker>

This bugreport has been first reported on the debian bug report system: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=992780

**Comment by perexg** [comment]
It's most likely a kernel driver issue. Please, report it at https://bugzilla.kernel.org .
