### ISSUE TITLE
Static build generates broken symlinks

### ISSUE THREAD

**Issue by daravi** [alsa-project/alsa-plugins#34]
Hello,

This snippet seems to generate some symlinks:
```
install-exec-hook:
	rm -f $(DESTDIR)@ALSA_PLUGIN_DIR@/libasound_module_rate_speexrate_*.so
	$(LN_S) libasound_module_rate_speexrate.so $(DESTDIR)@ALSA_PLUGIN_DIR@/libasound_module_rate_speexrate_best.so
	$(LN_S) libasound_module_rate_speexrate.so $(DESTDIR)@ALSA_PLUGIN_DIR@/libasound_module_rate_speexrate_medium.so
```

But it assumes we are doing a shared build. Which results in broken symlinks in a static build.

**Comment by tiwai** [comment]
Static build is disabled on alsa-plugins.

**Comment by daravi** [comment]
@tiwai Thanks. Just for my future reference, is this documented?

**Comment by tiwai** [comment]
This is a collection of external plugins, so it can be never static, per definition...

**Comment by daravi** [comment]
@tiwai I don't think your definition is correct:
https://gstreamer.freedesktop.org/documentation/gstreamer/gstplugin.html#gst_plugin_register_static

**Comment by tiwai** [comment]
Again, alsa-plugin is *external* plugins, so it's defined only for dynamic bindings.
