### ISSUE TITLE
mpv segfaults in a52 plugin

### ISSUE THREAD

**Issue by ykurlaev** [alsa-project/alsa-plugins#35]
When using mpv with the option `audio-device=alsa/<a52 device>` it gets a segfault on this line https://github.com/alsa-project/alsa-plugins/blob/da157e978d73f1947bb77637c324e19d003366d4/a52/pcm_a52.c#L566 because it calls `dump` before `prepare` has been called and `rec->avctx` is NULL.

**Comment by perexg** [comment]
Fixed in 286378b13e7db57666318fb794a787692a095b2c . Thank you for your report.
