### ISSUE TITLE
Error while building: storage size of ‘txtime_cfg’ isn’t known

### ISSUE THREAD

**Issue by Deepa-Santhosh** [alsa-project/alsa-plugins#41]
Hi,
I got the same error as reported by @kruemelbacke.

My Kernel version is > 4.19.
I also verified the installation of kernel headers using 
ls -l /usr/src/linux-headers-$(uname -r)

output:
total 1612
drwxr-xr-x 3 root root    4096 Nov 12 11:23 arch
lrwxrwxrwx 1 root root      39 Oct 22 14:16 block -> ../linux-hwe-5.4-headers-5.4.0-90/block
lrwxrwxrwx 1 root root      39 Oct 22 14:16 certs -> ../linux-hwe-5.4-headers-5.4.0-90/certs
lrwxrwxrwx 1 root root      40 Oct 22 14:16 crypto -> ../linux-hwe-5.4-headers-5.4.0-90/crypto
lrwxrwxrwx 1 root root      47 Oct 22 14:16 Documentation -> ../linux-hwe-5.4-headers-5.4.0-90/Documentation
lrwxrwxrwx 1 root root      41 Oct 22 14:16 drivers -> ../linux-hwe-5.4-headers-5.4.0-90/drivers
lrwxrwxrwx 1 root root      36 Oct 22 14:16 fs -> ../linux-hwe-5.4-headers-5.4.0-90/fs
drwxr-xr-x 4 root root    4096 Nov 12 11:23 include
lrwxrwxrwx 1 root root      38 Oct 22 14:16 init -> ../linux-hwe-5.4-headers-5.4.0-90/init
lrwxrwxrwx 1 root root      37 Oct 22 14:16 ipc -> ../linux-hwe-5.4-headers-5.4.0-90/ipc
lrwxrwxrwx 1 root root      40 Oct 22 14:16 Kbuild -> ../linux-hwe-5.4-headers-5.4.0-90/Kbuild
lrwxrwxrwx 1 root root      41 Oct 22 14:16 Kconfig -> ../linux-hwe-5.4-headers-5.4.0-90/Kconfig
drwxr-xr-x 2 root root    4096 Nov 12 11:23 kernel
lrwxrwxrwx 1 root root      37 Oct 22 14:16 lib -> ../linux-hwe-5.4-headers-5.4.0-90/lib
lrwxrwxrwx 1 root root      42 Oct 22 14:16 Makefile -> ../linux-hwe-5.4-headers-5.4.0-90/Makefile
lrwxrwxrwx 1 root root      36 Oct 22 14:16 mm -> ../linux-hwe-5.4-headers-5.4.0-90/mm
-rw-r--r-- 1 root root 1619639 Oct 22 14:16 Module.symvers
lrwxrwxrwx 1 root root      37 Oct 22 14:16 net -> ../linux-hwe-5.4-headers-5.4.0-90/net
lrwxrwxrwx 1 root root      41 Oct 22 14:16 samples -> ../linux-hwe-5.4-headers-5.4.0-90/samples
drwxr-xr-x 8 root root   12288 Nov 12 11:23 scripts
lrwxrwxrwx 1 root root      42 Oct 22 14:16 security -> ../linux-hwe-5.4-headers-5.4.0-90/security
lrwxrwxrwx 1 root root      39 Oct 22 14:16 sound -> ../linux-hwe-5.4-headers-5.4.0-90/sound
drwxr-xr-x 3 root root    4096 Nov 12 11:23 tools
lrwxrwxrwx 1 root root      40 Oct 22 14:16 ubuntu -> ../linux-hwe-5.4-headers-5.4.0-90/ubuntu
lrwxrwxrwx 1 root root      37 Oct 22 14:16 usr -> ../linux-hwe-5.4-headers-5.4.0-90/usr
lrwxrwxrwx 1 root root      38 Oct 22 14:16 virt -> ../linux-hwe-5.4-headers-5.4.0-90/virt

Seems like headers are included.
I also tried ./configure --prefix=/usr/local CFLAGS=-I/path/to/kernel/headers   as suggested by aguedes.

But the problem still persists.

My system specification :
Linux isl01-268 5.4.0-90-generic
Ubuntu 18.04.5 LTS
OS : 64 bits
Processor : Intel® Core™ i5-4570S CPU @ 2.90GHz × 4
Graphics : Intel® HD Graphics 4600 (HSW GT2)

Any help would be highly appreciated.

_Originally posted by @Deepa-Santhosh in https://github.com/alsa-project/alsa-plugins/issues/4#issuecomment-975138879_

**Comment by perexg** [comment]
Dup of #4 .
