### ISSUE TITLE
time to remove COPYING.GPL from alsa-plugins?

### ISSUE THREAD

**Issue by michael-mw-wang** [alsa-project/alsa-plugins#54]
It seems the only thing in alsa-plugins that could have a GPL license is rate/rate_samplerate.c, which has this at the top of the file:

 * This plugin code is supposed to be used and distributed primarily
 * under GPL v2 or later, in order to follow the license of libsamplerate.
 * However, if you already own a commercial license to use libsamplerate
 * for dynamic linking, this plugin code can be used and distributed also
 * under LGPL v2.1 or later.

In 2016, libsamplerate dropped its commercial license requirement and was released with the 2-Clause BSD license.   (See http://libsndfile.github.io/libsamplerate//license.html)

So I was wondering if the license for rate_samplerate.c can be updated to remove the GPLv2, which means the COPYING.GPL file can also be removed from the alsa-plugins package?

Thank you!

**Comment by tiwai** [comment]
The samplerate plugin is now LGPL-only.
But COPYING.GPL still remains because there is a header file in usb_stream that was copied from the kernel, which is GPL.

**Comment by michael-mw-wang** [comment]
OK, that is great! Thank you very much for taking care of this!

Michael


On Sat, Oct 7, 2023 at 12:32 AM Takashi Iwai ***@***.***> wrote:
>
> The samplerate plugin is now LGPL-only.
> But COPYING.GPL still remains because there is a header file in usb_stream that was copied from the kernel, which is GPL.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID: ***@***.***>

-- 
This electronic communication and the information and any files transmitted 
with it, or attached to it, are confidential and are intended solely for 
the use of the individual or entity to whom it is addressed and may contain 
information that is confidential, legally privileged, protected by privacy 
laws, or otherwise restricted from disclosure to anyone else. If you are 
not the intended recipient or the person responsible for delivering the 
e-mail to the intended recipient, you are hereby notified that any use, 
copying, distributing, dissemination, forwarding, printing, or copying of 
this e-mail is strictly prohibited. If you received this e-mail in error, 
please return the e-mail to the sender, delete it from your computer, and 
destroy any printed copy of it.
