### ISSUE TITLE
libavresample is deprecated since January 2017 swith to libswresample

### ISSUE THREAD

**Issue by marillat** [alsa-project/alsa-plugins#7]
As the subject said, would be nice if you can switch from libavresample  to libswresample

**Comment by quequotion** [comment]
@IdleGandalf has a [patch for this](https://git.harting.dev/anonfunc/alsa-plugins/commit/9cdbbb9874757b6f8fda7fb4ac2e3fc59da65946.patch)

Apparently it's been around since October 2019; not sure why no pull request was ever filed.

**Comment by marillat** [comment]
I'll apply this patch after the Debian `bullseye` release.

**Comment by manio** [comment]
This is probably now fixed with 8a3c0d795fbef5700c8cedcc82c6a337170c76ee

**Comment by perexg** [comment]
Yes, it should be. Closing.
